### ISSUE TITLE
Should typed-process ignore "resource vanished" errors when closing pipes?

### ISSUE THREAD

**Issue by expipiplus1** [fpco/typed-process#1]
At the moment running this code which calls a process which closes stdin will fail with `Main.hs: fd:12: hClose: resource vanished (Broken pipe)`. One has to manually close the handle ignoring a `ResourceVanished` `IOError`.

```haskell
module Main
  ( main
  ) where

import           GHC.IO.Exception
import           System.IO
import           System.IO.Error
import           System.Process.Typed

main :: IO ()
main =
  let pc = setStdin createPipe
         $ proc "ghc" ["-e", "System.IO.hClose System.IO.stdin"]
  in withProcess pc $ \p -> do
    let inn = getStdin p
    -- wait for the pipe to be closed
    _ <- waitExitCode p
    -- Use the pipe
    hPutStrLn inn "hello"
    -- Uncomment this to make things work
    -- handleResourceVanished (hClose inn)
    pure ()

handleResourceVanished :: IO a -> IO (Maybe a)
handleResourceVanished a =
  (Just <$> a) `catchIOError`
  (\e ->
     if ioeGetErrorType e == ResourceVanished
       then pure Nothing
       else ioError e)
```

**Comment by snoyberg** [comment]
I'm surprised by that behavior, but should be easy to work around. Would you be interested in sending a PR to check for and ignore the `ResourceVanished` exception?

**Comment by expipiplus1** [comment]
I can put it on my todo list, but can't make any promises about how soon it'll get to the top :)

**Comment by snoyberg** [comment]
On further investigation, I think things are behaving as expected, though the `Handle` API could give clearer exceptions. Consider what happens if we switch to `NoBuffering`:

```haskell
module Main
  ( main
  ) where

import           GHC.IO.Exception
import           System.IO
import           System.IO.Error
import           System.Process.Typed

main :: IO ()
main =
  let pc = setStdin createPipe
         $ proc "ghc" ["-e", "System.IO.hClose System.IO.stdin"]
  in withProcess pc $ \p -> do
    putStrLn "here1"
    let inn = getStdin p
    -- wait for the pipe to be closed
    _ <- waitExitCode p
    putStrLn "here2"
    hSetBuffering inn NoBuffering
    putStrLn "here3"
    -- Use the pipe
    hPutStrLn inn "hello"
    putStrLn "here4"
    -- Uncomment this to make things work
    -- handleResourceVanished (hClose inn)
    pure ()

handleResourceVanished :: IO a -> IO (Maybe a)
handleResourceVanished a =
  (Just <$> a) `catchIOError`
  (\e ->
     if ioeGetErrorType e == ResourceVanished
       then pure Nothing
       else ioError e)
```

I now get the much more intelligent error message:

```
here1
here2
here3
foo.hs: fd:14: hPutChar: resource vanished (Broken pipe)
```

The problem is that you're writing to a closed file descriptor. In your original example, this is only discovered when `hClose` tries to flush the buffer.

**Comment by expipiplus1** [comment]
It's certainly understandable why this happens. I suppose handling this case in typed-process is a courtesy to the users who probably don't care if the handle had vanished or not (I've only got my use case to go on here, so I could be wrong about that).

**Comment by snoyberg** [comment]
The exception in this case is perfectly valid: some data is being written to a file descriptor which is already closed. I'd argue that the real bug here is buffering behavior (I'm personally very much opposed to the presence of implicit buffering like this). But simply hiding an exception doesn't seem wise to me.

**Comment by expipiplus1** [comment]
Sounds reasonable. Perhaps a good solution would be to put some warning in the documentation about this case.

**Comment by snoyberg** [comment]
Sounds reasonable, do you have an idea of where to place it? It seems like
an obscure enough case that too prominent a position would be more
confusing than helpful.

**Comment by expipiplus1** [comment]
Perhaps on createPipe and useHandleClose? Where else can this occur?

**Comment by snoyberg** [comment]
It can occur on anything that creates a pipe, which may be additional
downstream functions, like createSink.

On Tue, Feb 28, 2017 at 10:52 AM, Joe Hermaszewski <notifications@github.com

**Comment by snoyberg** [comment]
Bump, I'm triaging issues. Did you want to send a doc PR?

**Comment by expipiplus1** [comment]
I don't have plans to send one at the moment, sorry!
