### ISSUE TITLE
Correct way to silence output?

### ISSUE THREAD

**Issue by fosskers** [fpco/typed-process#13]
Let's say I have a CLI tool...

```
> cooltool --awesome-option <some-args-here>
Working...
Output of child process here (via `runProcess`)...
Done!
>
```
but I'd like to provide an anti-verbosity command:
```
> cooltool --awesome-option -q <some-args-here>
Working...
Done!
>
```
where if `-q` exists, we want to ignore all output of the child process. Is the proper way to do this via `setStdout closed`? I have tried this, but the child process's output is still printed. Interestingly, it also conflicts with what the guide for this library says:

> This process now returns an `ExitFailure 1`, since it tries to write to a closed stdout file descriptor.

Is it better then to run `readProcess` (which does seem to suppress output) and ignore the returned `ByteString`? If I ignore it, will GHC optimize away the capturing process and not waste extra memory?

Thanks.

**Comment by snoyberg** [comment]
You can use ignored instead of closed. Do you need to apply it to stderr as
well?

**Comment by fosskers** [comment]
Hm, `ignored` doesn't seem to be an exposed symbol.

**Comment by snoyberg** [comment]
Apparently not, I just thought we had something like this. It would be a
good addition to the library. Does closing stderr fix the issue though?

**Comment by fosskers** [comment]
Oh, closing off `stderr` as well seems to fix it. That seems kind of odd... I'm pretty sure the child program I'm calling out to is outputting to stdout.

**Comment by fosskers** [comment]
Some nice data:

A shell-operation that was previously using `readProcess` and ignoring the output took 1m23s. It now takes 1m13s.

**Comment by fosskers** [comment]
Overall I'd call this solved. Thanks!
