### ISSUE TITLE
Convenience API for interleaved output? (stdout, stderr)

### ISSUE THREAD

**Issue by romanofski** [fpco/typed-process#16]
The API provides convenience functions to capture stdout and stderr handles. What happens often during tests is that test authors interacting with the the system need interleaved output from both stdout *and* stderr. That is especially important, when you run a frontend application and a backend application (e.g. HTTP) and need to debug communication failures. Dumping stdout and stderr separately can make debugging much harder, since you have to jump between the two outputs.

I currently get there with the functions in process-typed:

```Haskell
-- Demonstrates the concept.
readProcessWithErrorOutput :: FilePath -> [String] -> IO B.ByteString
readProcessWithErrorOutput cmd args = do
  (exitc, out) <- withProcess config $ \p -> atomically $ do
    e <- waitExitCodeSTM p
    stdout <- getStdout p
    pure (e, stdout)
  pure out
  where
    config = setStdin closed $ setStdout byteStringOutput $ setStderr (useHandleOpen stdout) $ proc cmd args
```

I'd like to ask if not such a high level function would fit into the typed-process API? If not that, perhaps another example in the documentation? Happy to contribute either or :)

**Comment by snoyberg** [comment]
I think I'd be OK with such a high level function added, given documentation explaining the motivation (like you've provided here). I think the word "interleaved" would be appropriate in the name of the function.
