### ISSUE TITLE
Possible Pipe leak?

### ISSUE THREAD

**Issue by 3noch** [fpco/typed-process#19]
Purely by observation it appears there is a pipe leak in `withProcessInterleave` if `withProcess` throws in the acquire portion of the `bracket`. Can someone confirm/deny? https://github.com/fpco/typed-process/blob/d8e1dabff1b09b0f3f8c6b87fb417b33ef964f5d/src/System/Process/Typed.hs#L854-L862

**Comment by 3noch** [comment]
I suppose  these handles *should* be GC'ed rather quickly, but that shouldn't justify improperly bracketing these resources to ensure prompt release.

**Comment by snoyberg** [comment]
Yes, that looks correct. You interested in sending a PR to fix this?

**Comment by 3noch** [comment]
Sure.
