### ISSUE TITLE
`closed` is almost never what you want, at least on Unixlikes

### ISSUE THREAD

**Issue by rjmac** [fpco/typed-process#23]
When `closed` is used to set any of the standard IO channels, those file descriptors are left unused in the child.  Since on posix systems, file descriptor creation is guaranteed to produce the lowest-numbered unused file descriptor, that means anything that opens a file or socket will first get the numbers of whatever was closed in the `ProcessConfig`, which is a recipe for unexpected behavior if the standard IO FDs are subsequently used by the process.

While actually closing is perhaps occasionally useful (though I can't think of a reason it would be anything but a lurking timebomb), I think that by far the least surprising behavior someone would want is creating the subprocess with the standard file descriptors open but attached to `/dev/null`, so writes are discarded and reads immediately report EOF.

I'm not sure if this is a request for a note about this in the docs for `closed` like the one on `NoStream` in the process package, or a request for changed behavior, since it's easy enough to open `/dev/null` and have the subprocess use it, if you're aware of what `closed` does.  It seems odd that that would take substantially more code than starting a subprocess with an unassigned standard FD, though.

**Comment by snoyberg** [comment]
How about an approach like the following:

* Add a new `nullPipe` (or similarly named) identifier which has the behavior you describe, with potential fallback on Windows where `/dev/null` isn't an option
* Add documentation to `closed` explaining that it has limitations, recommend `nullPipe`, and potentially deprecate it entirely.

Thoughts? Would you be interested in taking a stab at such a PR?

**Comment by rjmac** [comment]
Ok, I've got that PR finalized.  I talked to some people at work who are more in tune with the containers world than I am, and they believed that containers without a `/dev/null` would be quite rare and that anyone running such a thing would know that they'd have to do their homework to make sure it wouldn't break anything, so I removed the fallback I was worried about in the earlier versions of the PR, and it's all squashed neatly into one commit.
