### ISSUE TITLE
Allow any string-like type as an argument to a process?

### ISSUE THREAD

**Issue by kindaro** [fpco/typed-process#30]
It is a bit unfortunate that I have to use `String` for arguments to a process.

For instance, suppose I wish to obtain some data from a process and supply it to the other as an argument, like `ps $(id --user --name)`. I have to go as far as [utf8-string. Data. ByteString. Lazy. UTF8. toString][1] in order to make sure I have sensible handling of Unicode. All that while the data is delivered to the process as a C string array anyway, so, if anything, the arguments should be `ByteString`. In other cases I might have `Text` arguments, which I again must convert. `String` is the type I suppose it is agreed upon we should phase out.

[1]: https://hackage.haskell.org/package/utf8-string-1.0.1.1/docs/Data-ByteString-Lazy-UTF8.html

Looks like there is a package [tostring][2] that is specifically designed to solve this problem.

[2]: https://hackage.haskell.org/package/tostring

**Comment by snoyberg** [comment]
This isn't something I intend to include in this package. Any form of
automatic character encoding handling is likely to result in surprising
behavior for someone at some point. I wish we weren't using String as well,
but there is a long legacy of using it in the process package.

**Comment by kindaro** [comment]
I see.
