### ISSUE TITLE
Problems with setWorkingDir on macOS

### ISSUE THREAD

**Issue by k-bx** [fpco/typed-process#31]
Hi. I'm using a simple script that uses typed-process to run (and re-run) the webapp, but it behaves differently on Linux and macOS. My executable is located in `dist` folder, and should be launched as `./mywebapp`. Here's the script trying to launch it:

```haskell
#!/usr/bin/env stack
{- stack script
     --resolver=lts-13.24
     --package rio
     --package text
     --package string-class
     --package fsnotify
     --package directory
     --package process
     --package typed-process
-}
{-# LANGUAGE OverloadedStrings #-}

import qualified Control.Concurrent.MVar as MVar
import qualified Data.String.Class as S
import qualified Data.Text as T
import RIO
import System.Directory (canonicalizePath)
import System.Exit (ExitCode(..))
import qualified System.FSNotify as FSNotify
import System.Process.Typed

main :: IO ()
main = do
  webapp <- startProcess (setWorkingDir "./dist" (proc "./mywebapp" []))
  putStrLn "> started"
  threadDelay (2 * 1000000)
  stopProcess webapp
```

It works properly on Linux, while on macOS it gives:

```
run.hs: ./mywebapp: startProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

If you put `./dist/mywebapp` as a command, it will work on macOS, but not on Linux now. If you put `pwd` as a command, it will show a proper `/Users/kb/workspace/externalogic/dist` path including the `dist`.

**Comment by snoyberg** [comment]
I think this is an inherent difference in how Mac and Linux work. I've seen this behavior previously with the `process` package. Fixing this by standardizing on one behavior or the other could silently break existing code, so it's not clear that we can or should do something here.

**Comment by k-bx** [comment]
Introducing a new API and adding a big warning would be the least controversial first step IMO.

**Comment by snoyberg** [comment]
Can you provide a concrete proposal of what you'd like to see in terms of an API?

**Comment by k-bx** [comment]
I'm not sure what is the problem specifically so I don't know whether this API would fit the fix, but I would introduce something like `setWorkingDirConsistent` or `setWorkingDirCrossplatform` that would work as was expected by me (looking for an executable in `dist`), and put a warning on `setWorkingDir` that it might not work as expected (and link this issue maybe)

**Comment by k-bx** [comment]
I will spend some time later today to try to figure out what exactly is the issue on macOS.

**Comment by k-bx** [comment]
Reproduced without the typed-process, closing this, continuing there https://github.com/haskell/process/issues/171
