### ISSUE TITLE
question : is it possible to run a process and handle stdout and stderr lines during the run?

### ISSUE THREAD

**Issue by KasperJanssens** [fpco/typed-process#33]
Hi,

I have been trying a little twist on the current way of working of readProcess but have been failing up until now. 

The most obvious way of using this library seems to be reporting back the full contents of stdout and stderr at the end of the process, which was fine up until the moment we started launching long running processes and wanted to see their progress or their errors while they were still running.

So, my use case is that I need to launch a process and whenever a new line arrives on stdout or stderr I need to perform an IO action on it. 

I tried a few different things but have at best only been partially successful (meaning that the solution I have sometimes works and sometimes doesn't, and I do not understand what triggers it to fail). I don't think it is useful to report on them here as I get the strong feeling that I am making it too complicated and that I am missing something really obvious.

Would it be possible to give me a few pointers?

Kasper

**Comment by snoyberg** [comment]
It's definitely possible to interact with the running process. Here's an example from the test suite: https://github.com/fpco/typed-process/blob/7282d4551d7d915c0dd70f5715a53c2f837523a0/test/System/Process/TypedSpec.hs#L101-L113

**Comment by KasperJanssens** [comment]
Ok, I see. It is very similar to what I tried but for one reason or another my `hGetLine` didn't feel like returning anything, under certain circumstances, just blocked while I was sure there should be data on the handle.

Anyway, this answers my question, and what I was trying was maybe a bit error prone in the end, writing my own recursion, not unlike `byteStringFromHandle`. Will try using `sourceHandle` from conduit and try doing my thing that way. Thanks for the help.
