### ISSUE TITLE
Having a way for custom process kill.

### ISSUE THREAD

**Issue by qnikst** [fpco/typed-process#4]
This is merely a ticket for discussion the problem that I have.
Currently I can find no way in `typed-process` how to kill process using a special signal or have custom kill procedure. I have 3 cases in my mind:

  1. I spawn a haskell program that uses eventlogs or some exception handlers that I want to fire. In that case program should be killed with `SIGINT` otherwise there will be abnormal termination. So I want to stop program using signal I set. The issue is not unique to haskell programs, but does apprear in other cases.
  2. After the situation above I may end up with a situation where program ignores my signal in that case I want to send a SIGKILL after certain timeout. So I want my a way to write some procedure for killing process.
  3. I may want to interrupt process group instead of interrupting only one process.

This is possible with direct usage of the `process` if I start a waiting thread and then run `race waitingThread killing` procedure (with some additional checks), I can write an arbitrary complex killing procedure with some logging, that will be interrupted once program exits. Also such termination procedure will exit once process exit, but leaves a door for an abnormal cases when program can't be killed even by a sigint (for example if there is an unterruptible sleep). `typed-process` already provides waiting thread and nice API to get status, however it does not provide an access to underlying `ProcessHandle` so I have no way to write that procedure.

I'm not sure what would be the best wanted  way for  me. Some that I can think of:

1. Provide a new configuration setting that will allow to set custom shutdown procedure if that will have access to `Process` structure and `ProcessHandle` that would be enough for my case
2. Provide (potentially internal) access to `ProcessHandle` field, then I can write ```withProcess cfg $ \p -> ... `finally` (veryComplexKillProcedure (unsafeProcessHandle p)``` that will work and clean all allocated resources as necessary.

If there is a clear and agreed way forward I would be happy to volunteer and implement this feature.

**Comment by snoyberg** [comment]
Thanks for opening this up, let me get some points out in brief:

1. I'm totally on board with the idea of having a better way to send Unix signals to processes.
2. llowing some kind of customization of the internal logic for process killing seems fine, if tricky to get right (PRs for this will certainly be welcome).
3. I honestly thought I'd provided a function to access the internal `ProcessHandle`, but apparently I haven't. I see no reason _not_ to include one, especially if it comes from a `.Internal` module with big warnings about how dangerous it is.

So after getting those thoughts out, and reviewing your whole (very nicely written! thank you) description: if you can propose a way forward on the configuration setting, I'm OK with that. Making it not break the common cases accidentally may be tricky, but hopefully doable. And making it compatible with Windows may present a challenge. And `unsafeProcessHandle` is perfectly acceptable to me, that doesn't seem to need much more discussion.

**Comment by qnikst** [comment]
Seems that issue is resolved in #5. So I'm closing this. Thanks for the fast merge of that PR!

Maybe I'll reopen it if I find that there is a sane and safe way of making configuration setting.
