### ISSUE TITLE
Could we get a new release?

### ISSUE THREAD

**Issue by tomjaguarpaw** [fpco/typed-process#40]
I've just recommended typed-process over process on [a Reddit thread](https://www.reddit.com/r/haskell/comments/p2ck1c/best_way_to_call_python_from_haskell/h8j2xu4/). Could we get a new release (probably minor release?) so that the documentation improvements I made a while ago are available to users?

**Comment by snoyberg** [comment]
Good call. Sorry for the delay, I'd assumed that there'd be some other API change that would push this out sooner. 0.2.6.1 is now on Hackage.
