### ISSUE TITLE
I would like to comaintain typed-process

### ISSUE THREAD

**Issue by tomjaguarpaw** [fpco/typed-process#42]
I would like to comaintain typed-process. I don't expect to be able to solve the deepest of the technical problems but I would like to make sure the library has someone who can triage issues and help users as far as possible. I would also like to do a release of https://github.com/fpco/typed-process/pull/41 and then write a blog post/article explaining this library.

My Hackage username is [tomjaguarpaw](https://hackage.haskell.org/user/tomjaguarpaw).

**Comment by snoyberg** [comment]
That's awesome, great to have you on board! I've added you previously on GitHub, and have just given you Hackage permissions. Thank you!

**Comment by tomjaguarpaw** [comment]
> I've added you previously on GitHub

Hmm, I don't seem to have access. Perhaps I missed a GitHub collaboration request. Could you please send it again?

I'm releasing based on https://github.com/tomjaguarpaw/typed-process/ but it would be good to bring that to this repo.

**Comment by snoyberg** [comment]
I removed the old invite and sent a new one. Hopefully that will go through, let me know if there are any issues.

**Comment by tomjaguarpaw** [comment]
It's working, thanks!
