### ISSUE TITLE
Release 0.2.6.2

### ISSUE THREAD

**Issue by tomjaguarpaw** [fpco/typed-process#43]
@snoyberg and others, this is FYI. No need to reply unless you have concerns. Just wanted to give you a heads-up as this is my first time taking maintainership actions with this package.

I plan to merge a minor version bump (https://github.com/tomjaguarpaw/typed-process/commit/66c8b2f9cb8adbc5cd2c336c8b2e41202ed5ef22) to master and then release to Hackage. I don't think there's anything controversial here. I'll wait a few days in case you have comments.

(After my doc changes hit Hackage I plan to write up an article about this very nice library!)

**Comment by snoyberg** [comment]
Sounds good to me. IMO no need to wait, move ahead at whatever pace you’d like.

**Comment by tomjaguarpaw** [comment]
Thanks! Done: https://hackage.haskell.org/package/typed-process-0.2.6.2
