### ISSUE TITLE
Conduit dependency makes the package heavy

### ISSUE THREAD

**Issue by NightRa** [fpco/typed-process#6]
The `conduit` and `conduit-extras` dependencies of the package make this a heavy dependency, even though it would seem this is a light-weight package - a basic building block for many packages and applications.
(There are 42 recursive dependencies of the `typed-process` package, compared to 22, mostly base libraries, without the conduit dependencies.)

Could separating it to a `typed-process-conduit` package, or including a `typed-process` dependency in `conduit` itself be considered?

Have a nice day :)

**Comment by snoyberg** [comment]
Yes, that's the ultimate plan. I figured we'd have a lot more short term
API breakage making a separate package a pain, but so far the API has
remained stable. So I guess now is as good a time as any to split them up.
I'd like to keep them both in the same repo though. You interested in PRing
it?
