### ISSUE TITLE
Expose structure of `ProcessConfig` from internal module.

### ISSUE THREAD

**Issue by mpickering** [fpco/typed-process#62]
I wanted to write a wrapper of `runProcess` which would print out the command which was going to run before running it. However, the only way I have display a `ProcessConfig` is using the `Show` instance which prints out a lot more information (including full environment). 

Ideally it would be good to expose the structure of `ProcessConfig` via the internal module (so I can write the function myself).

**Comment by snoyberg** [comment]
I don't see a problem with that. @tomjaguarpaw any thoughts?

**Comment by tomjaguarpaw** [comment]
I'll defer to whatever is your preference, Michael.

I personally don't know immediately how to satisfy the request whilst being sure I'm not violating a desirable invariant or abstraction layer of this library, so it would be very low down my priority queue of Haskell-things-to-work-on.

That said I won't stand in you and @mpickering's way if you want to put together a change that tackles this issue. I'm also open to further discussion about it in case I've missed a reason why it's not easy enough for users to work around (for example by defining a wrapper type for `ProcessConfig`).

**Comment by tomjaguarpaw** [comment]
Oh, actually I think I misunderstood the request. I'm in support of exposing any internals from modules named `.Internal` as long as users know that they can't rely on their behavior or stability.

So I don't see a problem with this either.

**Comment by tomjaguarpaw** [comment]
Released here: https://hackage.haskell.org/package/typed-process-0.2.11.0
