### ISSUE TITLE
Add `TypeOperators` to `default-extensions` to suppress warnings with GHC >= 9.4

### ISSUE THREAD

**Issue by andreasabel** [fpco/typed-process#76]
The following warnings can be trivially pacified by adding `default-extensions: TypeOperators` in the cabal file.  This extension exists since GHC 5 (!), it is just no longer default since GHC 9.4.
```
Building library for typed-process-0.2.11.0...

src/System/Process/Typed/Internal.hs:113:17: warning: [GHC-58520] [-Wtype-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
113 | instance (stdin ~ (), stdout ~ (), stderr ~ ())
    |                 ^

src/System/Process/Typed/Internal.hs:113:30: warning: [GHC-58520] [-Wtype-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
113 | instance (stdin ~ (), stdout ~ (), stderr ~ ())
    |                              ^

src/System/Process/Typed/Internal.hs:113:43: warning: [GHC-58520] [-Wtype-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
113 | instance (stdin ~ (), stdout ~ (), stderr ~ ())
    |                                           ^

src/System/Process/Typed/Internal.hs:154:22: warning: [GHC-58520] [-Wtype-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
154 | instance (streamType ~ 'STInput, res ~ ())
    |                      ^

src/System/Process/Typed/Internal.hs:154:38: warning: [GHC-58520] [-Wtype-equality-requires-operators]
    The use of ‘~’ without TypeOperators
    will become an error in a future GHC release.
    Suggested fix: Perhaps you intended to use TypeOperators
    |
154 | instance (streamType ~ 'STInput, res ~ ())
    |                                      ^
```

**Comment by tomjaguarpaw** [comment]
`TypeOperators` is set in https://github.com/fpco/typed-process/blob/003bdab7b75458a22ff4bc1f6610cf389546e083/src/System/Process/Typed/Internal.hs#L3 and I indeed don't see any warning [in CI](https://github.com/fpco/typed-process/actions/runs/6443578363/job/17495675156#step:4:1184) so I'm confused what's going on here. 

Under what circumstances are you seeing these warnings? Is  `default-extensions: TypeOperators` supposed to do something that just putting `LANGUAGE` at the top of `Internals.hs` doesn't do?

**Comment by andreasabel** [comment]
Well the solution to this riddle is that typed-process-0.2.11.0 was uploaded in Feb while the `TypeOperators` pragma was only added in May.
> Uploaded by [tomjaguarpaw](https://hackage.haskell.org/user/tomjaguarpaw) at 2023-02-26

https://github.com/fpco/typed-process/blame/003bdab7b75458a22ff4bc1f6610cf389546e083/src/System/Process/Typed/Internal.hs#L3

**Comment by tomjaguarpaw** [comment]
Oh fine, OK. I didn't think to check what was actually released on Hackage. So this will become fixed in the next Hackage release. Please let me know if you think this is urgent so that I should make a Hackage release specifically to fix this issue.

**Comment by andreasabel** [comment]
Yes, sorry, I didn't check the codebase first, but then also, what matters for most of the users is what is released...
This is of course not urgent.
Maybe once 9.8 is out this could be released, because of the _magic 3_ (last 3 GHC versions principle---which is kind of magical thinking).

**Comment by tomjaguarpaw** [comment]
Yes, no problem. I appreciate the report. Divergences between the source repo and Hackage are always confusing (I ran into one for `singletons` yesterday) so ultimately I should aim to keep Hackage updated. Addressing your report sent me on a long yak shave trying to get CI to test more Stackage LTS versions so if I have the mental bandwidth I'll upload a new Hackage version when I've finished that.

**Comment by tomjaguarpaw** [comment]
OK, released the latest `master` as https://hackage.haskell.org/package/typed-process-0.2.11.1, including `TypeOperators`.

**Comment by andreasabel** [comment]
@tomjaguarpaw : Great, thanks!

Maybe add tag `typed-process-0.2.11.1` here?

**Comment by tomjaguarpaw** [comment]
Ah yes, done.
